### ISSUE TITLE
Add Discord/GitHub Icons+Links

### ISSUE THREAD

**Issue by evedes** [we-craft-code/we-craft-code#1]
We want to add Discord, GitHub, and Reddit links/buttons to our homepage.

Links: 
Discord invite: https://discord.com/invite/kp3NQNKW9J
GitHub Page: https://github.com/we-craft-code
Reddit Page: https://www.reddit.com/r/wecraftcode/

Please grab the icons from the react-icons package (which needs to be installed).

**Comment by ckvignesh** [comment]
Hi @evedes,

I've created a Heading Component that has buttons for WCC's socials.

Requesting you to check it and let me know what you think...

I've raised PR #6 for it, so the discussion can be continued there.


Thanks!

**Comment by ckvignesh** [comment]
I think this issue can be closed now, @evedes. Shall I close it?

**Comment by ckvignesh** [comment]
Thanks @evedes !
