### ISSUE TITLE
Add a flex container to our page so that everything scales correctly

### ISSUE THREAD

**Issue by evedes** [we-craft-code/we-craft-code#11]
Here's how our site shows up on big screens.
We want to scale the logo to be smaller, doesn't need to occupy such a larger area.

We want the view to be 100vh, not more (good when scroll bars disappear).

Use a flex container to show Header + Body correctly so that they scale up on any device or screen.

https://i.imgur.com/tmOkjyy.png

**Comment by ckvignesh** [comment]
Assigning this to @[joseXimenes](https://github.com/joseXimenes)
