### ISSUE TITLE
Add Tailwind CSS

### ISSUE THREAD

**Issue by evedes** [we-craft-code/we-craft-code#8]
We want to use [Tailwind](https://tailwindcss.com/) to do our CSS styling.

Please add tailwind CSS to the project and convert all the CSS contained in style props to tailwind classes.

You can follow this information on how to do it:
- https://tailwindcss.com/docs/guides/remix
- https://remix.run/docs/en/v1/guides/styling

**Comment by joseXimenes** [comment]
Hi Eduardo, just finish it, may i submit a pull request?

**Comment by evedes** [comment]
Hey @joseXimenes , long time no see! Sure, just PR it! Thanks!

We have a board to control the ongoing issues, so next time make sure you assign the task to you first to avoid overlapping with other peoples'. 🙏🏻 ❤️  https://github.com/orgs/we-craft-code/projects/2
